name: Secure CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SSH_USER: ${{ secrets.SSH_USERNAME }}

jobs:
 
  sast-analysis:
    runs-on: ubuntu-latest
    name: SAST Security Scanning
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: SAST with Bandit
      run: |
        pip install bandit
        bandit -r . -f json -o reports/bandit-report.json
      continue-on-error: true
    
    - name: Semgrep Analysis
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/security-audit
        output: reports/semgrep-report.json
    
    - name: Upload SAST reports
      uses: actions/upload-artifact@v4
      with:
        name: sast-reports
        path: reports/

  
  secret-scan:
    runs-on: ubuntu-latest
    name: Secrets Detection
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Detect secrets with TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        args: --json --regex --entropy=False github.com/${{ github.repository }}
    
    - name: Gitleaks scanning
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .gitleaks.toml
