name: Secret scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ] 

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Run TruffleHog secrets scan
      run: |
        docker run --rm -v "$(pwd):/workdir" trufflesecurity/trufflehog:latest github --repo=https://github.com/cms-dev/cms --json || echo "Secrets scan completed"
